name: gstcefsrc pull request test

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Run gstcefsrc tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: |
          sudo apt-get install --yes libgstreamer1.0-0 libgstreamer-plugins-base1.0-dev

      - name: Cache
        id: cache-cmake
        uses: actions/cache@v2
        with:
          path: |
            build/
            third_party/
          key: ${{ hashFiles('cmake/DownloadCEF.cmake') }}-${{ hashFiles('CMakeLists.txt') }}-cache

      - name: cmake
        if: steps.cache-cmake.outputs.cache-hit != 'true'
        run: |
          mkdir -p build && cd build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..

      - name: make
        run: |
          cd build
          make -j
          echo $GST_PLUGIN_PATH
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./node_modules
          options: -screen 0 1920x1080x60
          run: gst-launch-1.0 -e \ cefsrc url="https://soundcloud.com/platform/sama" ! \ video/x-raw, width=1920, height=1080, framerate=60/1 ! \ cefdemux name=demux ! queue ! videoconvert ! \ queue max-size-bytes=0 max-size-buffers=0 max-size-time=3000000000 ! x264enc ! queue ! \ mp4mux name=muxer ! filesink location='test.mp4' \ audiotestsrc do-timestamp=true is-live=true  volume=0.0 ! audiomixer name=mix ! \ queue max-size-bytes=0 max-size-buffers=0 max-size-time=3000000000 ! audioconvert ! \ audiorate ! audioresample ! faac bitrate=128000 ! queue ! muxer. \ demux. ! queue ! mix.
