name: gstcefsrc pull request test

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Run gstcefsrc tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: |
          sudo apt-get install --yes libgstreamer1.0-0 libgstreamer-plugins-base1.0-dev

      - name: Cache
        id: cache-cmake
        uses: actions/cache@v2
        with:
          path: |
            build/
            third_party/
          key: ${{ hashFiles('cmake/DownloadCEF.cmake') }}-${{ hashFiles('CMakeLists.txt') }}-cache

      - name: cmake
        if: steps.cache-cmake.outputs.cache-hit != 'true'
        run: |
          mkdir -p build && cd build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..

      - name: make
        run: |
          cd build
          make -j

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          options: -screen 0 1920x1080x60
          run: gst-launch-1.0 \ cefbin name=cef cefsrc::url="https://soundcloud.com/platform/sama" \ cef.video ! video/x-raw, width=1920, height=1080, framerate=60/1 ! videoconvert ! xvimagesink \ cef.audio ! audioconvert ! audiomixer ! autoaudiosink
